import React from 'react'
import {AiFillLinkedin, AiFillGithub} from 'react-icons/ai'
import Projects from './Projects'
import Navbar from './Navbar'

export default function Home() {
  return (
    <div>
      <head>
        <title>Portfolio Elisa Rogge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>

      <main className='bg-white'>
        <Navbar />
        <div className='text-center p-10'>
          <h2 className='text-5xl py-2 text-teal-600 font-medium'>Elisa Rogge</h2>
          <h3 className='text-2xl py-2'>Développeuse Full-Stack</h3>
          <p className='text-md py-5 leading-8 text-gray-800'>Bienvenue sur mon portfolio ! Je vais vous présenter mes nombreux projets personnels ou professionnels ainsi que mes compétences dans les langages appris.</p>
        </div>
        <div className='text-5xl flex justify-center gap-16 py-3 text-gray-800'>
          <AiFillLinkedin />
          <AiFillGithub />
        </div>
        <div className="mx-auto w-80 h-80 ">
          {/* <Image src={elisa}/> */}
        </div>
      <Projects/>
      </main>

      
    </div>
  )
}
